name: Publish to npm

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # 选择适合你项目的Node.js版本
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm install

    - name: Bump version and tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_annotated_tag: true

    - name: Create Release
      if: steps.tag_version.outputs.new_tag != ''
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: ${{ steps.tag_version.outputs.new_tag }}
        draft: false
        prerelease: false

    - name: Publish to npm
      if: steps.tag_version.outputs.new_tag != ''
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
